require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - '.gem/**/*'
    - 'hawkr.gemspec'

Metrics/LineLength:
  Max: 400

Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  Enabled: false

RSpec/ExampleLength:
  Max: 15

Layout/EmptyLinesAroundArguments:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false
