version: '2'

services:
  db:
    image: timescale/timescaledb:0.8.0-pg10
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hawkr_db

  web:
    build: .
    command: bin/deploy
    environment:
      RUNSERVER: 1
      PORT: 9292
    ports:
      - "9292:9292"
    depends_on:
      - db
    links:
      - db

  parser:
    build: .
    command: bin/deploy
    environment:
      RUN: 1
      PORT: 9393
    depends_on:
      - db
    links:
      - db
