version: '2'

volumes:
  redis:
  postgres:

services:
  db:
    image: timescale/timescaledb:0.8.0-pg10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hawkr_db
    volumes:
      - "postgres:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    command: redis-server --port 6380
    volumes:
      - "redis:/var/lib/redis/data"

  web:
    build: .
    command: bin/deploy
    environment:
      RUNSERVER: 1
      PORT: 9292
    ports:
      - "9292:9292"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis

  parser:
    build: .
    command: bin/deploy
    environment:
      RUN: 1
      PORT: 9393
    depends_on:
      - db
    links:
      - db
